### ISSUE TITLE
Unable to Preview when in Draft mode

### ISSUE THREAD

**Issue by darshan-g** [danestves/strapi-plugin-preview-content#10]
As soon as I start editing the content, the Preview button gets disabled. The only button that is enabled at this point is the 'Save' button. And as soon as I hit the 'Save' button, the content gets published.

When I unpublish, i.e. when I am in Draft mode, and I try to Preview, there's no data coming from the GraphQl query.

So, how exactly would Preview functionality work? Can someone please let me know if I am missing something?

I am on the latest Strapi version which is 3.5.4 

Your response would be much appreciated.

Thanks.

**Comment by danestves** [comment]
And also in the GraphQL query you need to add `publicationState: "PREVIEW"` because is the way Strapi handle that

**Comment by darshan-g** [comment]
That helped @danestves. Thank u so much for the prompt response.

But if I make some edits to already published content and want to preview my changes before re-publishing, I can't really do that right? Because as soon as I save the content it is getting published. 

Is there a way we can Preview the edited content before re-publishing?

**Comment by danestves** [comment]
With the actual Strapi sadly no 😢  that how Strapi works actually, hope that one day they can change that

**Comment by darshan-g** [comment]
Anyway, Thanks again!! Much Appreciated :)
