### ISSUE TITLE
Custom param for preview URL

### ISSUE THREAD

**Issue by darshan-g** [danestves/strapi-plugin-preview-content#11]
Hi @danestves 

Currently we just have contentType and id as params to the preview URL. For the single types i am always getting id as 1. The contentType is generated by Strapi and is not customizable. 

I want to have a custom param so that i can use it to redirect to the actual UI route.

Is there a way we can set a custom param (e.g. pageId)?

**Comment by danestves** [comment]
Hi, currently there is no a way to do it, but is a good feature
