### ISSUE TITLE
Create documentation on how to contribute

### ISSUE THREAD

**Issue by pr0gr8mm3r** [danestves/strapi-plugin-preview-content#12]
The repository structure makes it rather hard to test changes in a local test environment. I tried cloning this repository into an existing strapi application's plugins folder, but because the files are all in the src folder instead of root, it doesn't build. I couldn't figure out a way to set it up correctly.

I believe it would be beneficial to the project if there were guidance on how to set this up.

**Comment by danestves** [comment]
Thanks i will work on this!
