### ISSUE TITLE
Settings menu disappears when plugin installed

### ISSUE THREAD

**Issue by sharpn** [danestves/strapi-plugin-preview-content#18]
Whenever i setup the plugin the settings menu from the left of the app goes missing.

**To Reproduce**
- create a new strapi project
- run `strapi develop` and see settings section available
- install the plugin and add the files to extensions
- run `strapi develop` again and see the section disappeared

Using latest version of strapi 3.6.1, uninstalling the plugin brings back the settings menu

**Comment by danestves** [comment]
Thanks i will review it in the last change, are you using the latest version of the plugin? The latest version is `1.0.2`

**Comment by danestves** [comment]
Hey @polcode-dzielonka you think you can help with this?

**Comment by sharpn** [comment]
@danestves hey, yea i have also gone through all the versions `1.0.0`, `1.0.1` and `1.0.2` and they all seem to cause the issue

**Comment by danestves** [comment]
@sharpn updated to `v1.1.0` https://github.com/danestves/strapi-plugin-preview-content/blob/main/CHANGELOG.md#110-2021-05-05 update the package and tell me if is working now

**Comment by blb78** [comment]
Hello @danestves , I can confirm that it works now with `v1.1.0`

**Comment by danestves** [comment]
I'm going to proceed to close this issue, thank you guys!

**Comment by sharpn** [comment]
@danestves @blb78 sorry totally missed this, can also confirm that 1.1.0 has fixed the issue. Thanks
