### ISSUE TITLE
There is no preview button in list view.

### ISSUE THREAD

**Issue by SalahAdDin** [danestves/strapi-plugin-preview-content#19]
Hi, i'm testing your plugin in local view and it looks cool, both preview and clone button are visible in the detailed views, but not the preview icon in list view:
![image](https://user-images.githubusercontent.com/5034215/118196506-cc6f5400-b455-11eb-98b3-93b03e616d94.png)

Why?

I'm using the last version with the last **Strapi** version too.

Thanks.

**Comment by danestves** [comment]
Thanks @SalahAdDin i'm going to check that this weekend

**Comment by SalahAdDin** [comment]
Hope I didn't imported it wrong.

**Comment by blk-franck** [comment]
Any update about this issue? We have the same one.
Thank you.

**Comment by SalahAdDin** [comment]
@danestves Had you time to review this? It still happens with the latest version.

Thanks.

**Comment by danestves** [comment]
Hi guys! I'm trying to find the error but until now, i can't see what was causing this

**Comment by SalahAdDin** [comment]
> Hi guys! I'm trying to find the error but until now, i can't see what was causing this

Maybe if you hint us we could get any log or something to help you realize which is the error.

I migrated my portfolio from `3.x.x` to `3.6.x`, i deleted both `.cache` and `build` folders and rebuilded the admin.

Maybe something is missing from models' settings.

What do you think?

**Comment by danestves** [comment]
Yeah! The problem is with the `strapi-files` because we edit the template from the table to show or not the `eye` icon

**Comment by SalahAdDin** [comment]
> Yeah! The problem is with the `strapi-files` because we edit the template from the table to show or not the `eye` icon

And you mean? Must we check on the **Strapi** files? Did you review them?

**Comment by danestves** [comment]
Yeah! This is the path https://github.com/danestves/strapi-plugin-preview-content/tree/main/strapi-files/v3.6.x/extensions/content-manager/admin/src/components/CustomTable inside CustomTable are the files to override that table

**Comment by SalahAdDin** [comment]
> Yeah! This is the path https://github.com/danestves/strapi-plugin-preview-content/tree/main/strapi-files/v3.6.x/extensions/content-manager/admin/src/components/CustomTable inside CustomTable are the files to override that table

so, what should we check here?

**Comment by danestves** [comment]
https://github.com/danestves/strapi-plugin-preview-content/blob/main/strapi-files/v3.6.x/extensions/content-manager/admin/src/components/CustomTable/Row/index.js#L39 in this line i active the eye icon

**Comment by SalahAdDin** [comment]
> https://github.com/danestves/strapi-plugin-preview-content/blob/main/strapi-files/v3.6.x/extensions/content-manager/admin/src/components/CustomTable/Row/index.js#L39 in this line i active the eye icon

I was thinking about... maybe as we are migrating existing pages, posts, etc., they have no the previewable option by default, do they have?

What do you think?

**Comment by armaaar** [comment]
@SalahAdDin I added a PR with a fix for the problem here: #24 

It's a really simple one line you need to add. You can find it here: https://github.com/danestves/strapi-plugin-preview-content/pull/24/files

**Comment by SalahAdDin** [comment]
> @SalahAdDin I added a PR with a fix for the problem here: #24
> 
> It's a really simple one line you need to add. You can find it here: https://github.com/danestves/strapi-plugin-preview-content/pull/24/files

How did you find it?

**Comment by danestves** [comment]
Thank you @SalahAdDin for the report and @armaaar for the fix!! In a few minutes the package will have a new version!
