### ISSUE TITLE
Preview Content API only available if published

### ISSUE THREAD

**Issue by Buooy** [danestves/strapi-plugin-preview-content#3]
Can I double check if the expected behavior is that the preview content api url e.g.`/preview-content/items/123` is only available when the item is published?

If it is, I'm wondering how to use it for previews? Would it not make more sense to allow the preview api url to be available ONLY to items that are in draft mode?

**Comment by danestves** [comment]
It's available when is published or draft, think in a static generation site (like nextjs) and even if your content type is published you make changes and instantly can go to see the preview content of that

**Comment by Buooy** [comment]
ok noted on this. thanks for the clarification
