### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Radlad-io** [danestves/strapi-plugin-preview-content#4]
I would love to use this plugin with Nextjs but this part of the documentation isn't very clear. Would you be able to elaborate?

**📁 Copy required files**
Inside strapi-files we have a list of folders with the Strapi version, enter to the version that correspond with your installation, and you will see this files

It seems like files from the Admin panel need to be ejected but it's not clear. 

Thank you in advance for any help you can provide!

**Comment by danestves** [comment]
Hi! You need to go to this folder:
![image](https://user-images.githubusercontent.com/31737273/108389648-404ae900-71e6-11eb-9495-abb2d9be50fe.png)

Enter to the version that correspond with the actual strapi version:
![image](https://user-images.githubusercontent.com/31737273/108389727-53f64f80-71e6-11eb-9582-892b5a416348.png)

And copy the required files, you can see this folder there:
![image](https://user-images.githubusercontent.com/31737273/108389824-6a9ca680-71e6-11eb-9557-dd79c09c6b27.png)

That files you need to copy it in the root of your strapi project

**Comment by Radlad-io** [comment]
Maybe I'm missing something, but those files don't seem to be present after installing via NPM or Yarn.

This is what I'm getting after installing via NPM.

<img width="300" alt="Screen Shot 2021-02-18 at 6 45 53 PM" src="https://user-images.githubusercontent.com/24879510/108437483-7191dc00-721b-11eb-8708-a3b28b5388cd.png">

**Comment by danestves** [comment]
Hi! You need yo manually copy the files from GitHub (extensions) and put it in the root of your project, not inside node_modules

**Comment by Radlad-io** [comment]
OHHHHHHHHH. Thank you so much! I was able to get this to work. I have a feeling that this will be one of the most popular Strapi plugins. Great work.

**Comment by Axel-KIRK** [comment]
Maybe it should be said in the readme, like : "in our repository, not on your local project"
