### ISSUE TITLE
Allow more URLs

### ISSUE THREAD

**Issue by abdonrd** [danestves/strapi-plugin-preview-content#5]
I have a project with different ways to create the URLs. Example:

`Competition` model has a `slug` field:
- URL: `domain.com/competition/:slug`

`Season` model has a `slug` field and a relation with `Competition`:
- URL: `domain.com/competition/:competitionSlug/:seasonSlug`

`Profile` model has a `username` field:
- URL: `domain.com/profile/:username`

**Comment by danestves** [comment]
Hi @abdonrd! Thanks for the issue but at the moment we only create one preview link with contentType and Id, and you need to do the rest of the logic
