### ISSUE TITLE
Response skips collection's custom controllers

### ISSUE THREAD

**Issue by selfagency** [danestves/strapi-plugin-preview-content#6]
Thanks for making this. It's great. One issue I'm running into, however, is that the data I get back skips over my custom controllers where I parse Markdown into HTML and swap out S3 URLs for my CDN, so all that formatting gets lost. Is there a way to get it to return the data after it's been processed by the controller? Thanks.

**Comment by danestves** [comment]
Hi @selfagency ! Thank you, can you tell me what frontend are you using to give you a solution?

**Comment by selfagency** [comment]
I'm using Nuxt, but I don't want to do those things in my Nuxt application, which is why I coded them as Strapi controllers.

**Comment by selfagency** [comment]
I think you misunderstand my problem. This is what Strapi does when I fetch posts from my `posts` endpoint:

```javascript
'use strict'
const axios = require('axios')
const { StrapiMarkdown, fieldsByType } = require('strapi-markdown-parser')
const StrapiCdnUrlRewrite = require('strapi-cdn-url-rewrite')
const { sanitizeEntity } = require('strapi-utils')
const model = require('../models/posts.settings.json')

const { md } = new StrapiMarkdown(fieldsByType(model, ['richtext', 'text']), fieldsByType(model, ['string']))
const { cdnRewrite } = new StrapiCdnUrlRewrite()

const oembed = async url => {
  try {
    const endpoint = `${process.env.OEMBED_ENDPOINT}?url=${url}`
    return (await axios(endpoint)).data.html
  } catch (err) {
    console.error(err)
  }
}

module.exports = {
  async find(ctx) {
    try {
      let data = await strapi.services.posts.find(ctx.query)
      data = await Promise.all(
        data.map(async item => {
          if (item.embed) item.embed = await oembed(item.embed)
          sanitizeEntity(item, { model: strapi.models.posts })
          return item
        })
      )
      data = md(cdnRewrite(data))
      return data
    } catch (err) {
      console.error(err)
    }
  },
  async findOne(ctx) {
    try {
      const data = await strapi.services.posts.findOne({ id: ctx.params.id })
      if (data && data.embed) {
        data.embed = await oembed(data.embed)
        return md(cdnRewrite(sanitizeEntity(data, { model: strapi.models.posts })))
      } else {
        return undefined
      }
    } catch (err) {
      console.error(err)
    }
  }
}
```

This generates [formatted HTML from the Markdown](https://www.npmjs.com/package/strapi-markdown-parser) stored in Strapi's database, rewrites the URLs of images to my CDN, queries oEmbed data, and sanitizes private fields.

Here's how it looks on the front-end:

![image](https://user-images.githubusercontent.com/2541728/109749503-cd0f8280-7ba8-11eb-9d47-6e2ae9bf3b59.png)

When I get my data back from the `preview-content` endpoint, none of my changes to the posts performed in the above controller are there. 

![image](https://user-images.githubusercontent.com/2541728/109749517-d39dfa00-7ba8-11eb-9ac4-47268296b544.png)

**Comment by danestves** [comment]
Yeah, what i mean is that the endpoint from `preview-content` is used only for normal content, if you have transformations or more, it's even better to use the normal endpoint where you have the controller. In our company we use the normal route to make the request and the preview only to get the id and the content type, if you want i can make you examples

**Comment by selfagency** [comment]
Ah gotcha, thanks

**Comment by danestves** [comment]
Always happy to help 🙌
